version: '3.8'
services:
  api-gateway:
     build: ./backend
     ports:
       - "8000:8000"
     env_file:
       - ./backend/.env
     depends_on:
      - rabbitmq
      - redis
  email-microservice:
     build: ./Email-microservice
     env_file:
       - ./Email-microservice/.env
     depends_on:
      - rabbitmq    

  payment-microservice:
     build: ./Payment-microservice
     env_file:
      - ./Payment-microservice/.env
     depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    ports:
     - "5672:5672"
     - "15672:15672"

  redis:
   image: redis:latest
   ports:
    - "6379:6379"   
      
        